;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.Activate.Dash",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Dash",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Jump",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Active.Dash",DevComment="")
+GameplayTagList=(Tag="Status.Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Status.Stamina.Regen",DevComment="")

